//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _7Gplus
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GEntities : DbContext
    {
        public GEntities()
            : base("name=GEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tFuturo> tFuturos { get; set; }
        public virtual DbSet<tPppsEuroUsd> tPppsEuroUsds { get; set; }
        public virtual DbSet<tCPIu> tCPIus { get; set; }
        public virtual DbSet<tCPIeu> tCPIeux { get; set; }
        public virtual DbSet<tbondUS10Y> tbondUS10Y { get; set; }
        public virtual DbSet<tbondEU10Y> tbondEU10Y { get; set; }
        public virtual DbSet<tFxEURUSD> tFxEURUSDs { get; set; }
        public virtual DbSet<tZoneTime> tZoneTimes { get; set; }
        public virtual DbSet<tpikitosT> tpikitosT { get; set; }
        public virtual DbSet<tConsola> tConsola { get; set; }
        public virtual DbSet<tPppsEuroUsdDaily> tPppsEuroUsdDaily { get; set; }
        public virtual DbSet<tEURUSDfed> tEURUSDfed { get; set; }
        public virtual DbSet<tGlobex> tGlobex { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tFuturosCMEquotes> tFuturosCMEquotes { get; set; }
        public virtual DbSet<tOpcionesCMEquotes> tOpcionesCMEquotes { get; set; }
        public virtual DbSet<tCotizacionSpot> tCotizacionSpot { get; set; }
        public virtual DbSet<LineaTendeciaFuturos> LineaTendeciaFuturos { get; set; }
        public virtual DbSet<ResumenOpciones> ResumenOpciones { get; set; }
    }
}
