//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _7Gplus
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineaTendeciaFuturos
    {
        public int id { get; set; }
        public string Tipo { get; set; }
        public Nullable<double> x { get; set; }
        public Nullable<double> y { get; set; }
        public Nullable<System.DateTime> Acttualizacion { get; set; }
        public Nullable<System.DateTime> ActtualizacionCME { get; set; }
    }
}
