//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _7Gplus
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCotizacionSpot
    {
        public int id { get; set; }
        public double Close { get; set; }
        public Nullable<System.DateTime> Change { get; set; }
        public Nullable<double> Open { get; set; }
        public Nullable<double> High { get; set; }
        public Nullable<double> Low { get; set; }
        public Nullable<double> Volume { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<double> VolUSD { get; set; }
        public Nullable<double> VolEUR { get; set; }
    }
}
