//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _7Gplus
{
    using System;
    using System.Collections.Generic;
    
    public partial class tFxEURUSD
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<double> open { get; set; }
        public Nullable<double> high { get; set; }
        public Nullable<double> low { get; set; }
        public Nullable<double> close { get; set; }
        public Nullable<double> volume { get; set; }
    }
}
