//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _7Gplus
{
    using System;
    using System.Collections.Generic;
    
    public partial class tGlobex
    {
        public int @int { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> endContractDate { get; set; }
        public Nullable<double> Last { get; set; }
        public Nullable<double> Change { get; set; }
        public Nullable<double> PriorSettle { get; set; }
        public Nullable<double> Open { get; set; }
        public Nullable<double> High { get; set; }
        public Nullable<double> Low { get; set; }
        public Nullable<double> Volume { get; set; }
        public Nullable<double> HiLowLimit { get; set; }
    }
}
