//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _7Gplus
{
    using System;
    using System.Collections.Generic;
    
    public partial class tpikitosT
    {
        public int id { get; set; }
        public Nullable<double> pFXclose { get; set; }
        public Nullable<double> pCMEclose { get; set; }
        public Nullable<double> pPPAclose { get; set; }
        public Nullable<double> diasCicloFuturos { get; set; }
        public Nullable<double> diasCicloPPA { get; set; }
        public Nullable<double> tipoCilcoFuturos { get; set; }
        public Nullable<double> tipoCilcoPPA { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<double> pikito { get; set; }
        public Nullable<double> Rpikito { get; set; }
        public Nullable<double> pCMEproy { get; set; }
        public Nullable<double> pPPAproy { get; set; }
        public Nullable<double> TcProm { get; set; }
        public Nullable<double> TcCorte { get; set; }
    }
}
